- name: Example Ansible handbook for updating nginx content
  hosts: all
  remote_user: ubuntu
  roles:
  - handlers

  handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
