- name: Update apt cache and install nginx on server B
  become: true
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: remove default index page
  file:
    path: /var/www/html/index.html
    state: absent
  become: true

- name: index.html copy
  template: src=index.html dest=/var/www/html/index.html
  become: true

## Update the content on website
- name: updated.html file
  template: src=updated.html dest=/var/www/html/updated.html
  notify:
  - Restart Nginx
  become: true

- name: Rename updated.html to index.html
  command: mv /var/www/html/updated.html /var/www/html/index.html
  args:
    removes: /var/www/html/index.html # Only run if original file exists
  become: true

# server_b ansible_host=18.130.180.247 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
